
<br>
Day 1: NumPy Basics<br>
Applying Linear Algebra knowledge to Python<br>


In [3]:
import numpy as np

In [ ]:
print("=" * 70)
print(" NUMPY: LINEAR ALGEBRA IN PYTHON")
print("=" * 70)

============================================================================<br>
# 1. CREATING ARRAYS (20 min)<br>
============================================================================

In [1]:
print("\n1. CREATING NUMPY ARRAYS")
print("-" * 70)


1. CREATING NUMPY ARRAYS
----------------------------------------------------------------------


From lists

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1}")
print(f"Shape: {arr1.shape}, Dtype: {arr1.dtype}")

1D Array: [1 2 3 4 5]
Shape: (5,), Dtype: int64


2D array (matrix)

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array (Matrix):\n{matrix}")
print(f"Shape: {matrix.shape}, Dimensions: {matrix.ndim}")


2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3), Dimensions: 2


Special arrays

In [7]:
zeros = np.zeros((3, 3))
print(f"\nZeros matrix:\n{zeros}")


Zeros matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
ones = np.ones((2, 4))
print(f"\nOnes matrix:\n{ones}")


Ones matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
identity = np.eye(3)
print(f"\nIdentity matrix:\n{identity}")


Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
random_matrix = np.random.rand(3, 3)
for row in random_matrix:
    for i in range(len(row)):
        row[i] = int(round(row[i]*10, 0))

    # for val in row:
    #     row[row.tolist().index(val)] = int(round(val*10, 0))
print(f"\nRandom matrix:\n{random_matrix}")


Random matrix:
[[7. 8. 8.]
 [4. 7. 5.]
 [8. 9. 2.]]


Range

In [13]:
sequence = np.arange(0, 10, 2)  # start, stop, step
print(f"\nSequence: {sequence}")


Sequence: [0 2 4 6 8]


In [ ]:
linspace = np.linspace(0, 1, 11)  # start, stop, num_points
print(f"Linspace: {linspace}")

Linspace: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


============================================================================<br>
2. ARRAY INDEXING & SLICING (15 min)<br>
============================================================================

In [ ]:
print("\n2. INDEXING & SLICING")
print("-" * 70)

In [37]:
arr = np.array([10, 20, 30, 40, 50])
print(f"Array: {arr}")
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")
print(f"Slice [1:4]: {arr[1:4]}")

Array: [10 20 30 40 50]
First element: 10
Last element: 50
Slice [1:4]: [20 30 40]


In [22]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nMatrix:\n{matrix}")
print(f"Element [0, 0]: {matrix[0, 0]}")
print(f"First row: {matrix[0, :]}")
print(f"First column: {matrix[:, 0]}")
print(f"Submatrix [0:2, 0:2]:\n{matrix[0:2, 0:2]}")


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element [0, 0]: 1
First row: [1 2 3]
First column: [1 4 7]
Submatrix [0:2, 0:2]:
[[1 2]
 [4 5]]


Boolean indexing

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"\nArray: {arr}")
print(f"Elements > 3: {arr[arr > 3]}")
print(f"Even elements: {arr[arr % 2 == 0]}")


Array: [1 2 3 4 5 6]
Elements > 3: [4 5 6]
Even elements: [2 4 6]


============================================================================<br>
3. ARRAY OPERATIONS (20 min)<br>
============================================================================

In [ ]:
print("\n3. ARRAY OPERATIONS")
print("-" * 70)

In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [43]:
print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}  (element-wise)")
print(f"a / b = {a / b}")
print(f"a ** 2 = {a**2}")

a = [1 2 3 4]
b = [5 6 7 8]
a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]  (element-wise)
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]


Scalar operations

In [ ]:
print(f"\na * 2 = {a * 2}")
print(f"a + 10 = {a + 10}")

Matrix operations (YOU KNOW THIS FROM LINEAR ALGEBRA!)

In [1]:
print("\n4. MATRIX OPERATIONS (Linear Algebra!)")
print("-" * 70)


4. MATRIX OPERATIONS (Linear Algebra!)
----------------------------------------------------------------------


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [5]:
print(f"Matrix A:\n{A}")
print(f"\nMatrix B:\n{B}")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


Matrix multiplication (@ operator)

In [6]:
print(f"\nA @ B (Matrix multiplication):\n{A @ B}")


A @ B (Matrix multiplication):
[[19 22]
 [43 50]]


Element-wise multiplication

In [7]:
print(f"\nA * B (Element-wise):\n{A * B}")


A * B (Element-wise):
[[ 5 12]
 [21 32]]


Transpose

In [8]:
print(f"\nA.T (Transpose):\n{A.T}")


A.T (Transpose):
[[1 3]
 [2 4]]


Determinant (requires linalg)

In [9]:
det_A = np.linalg.det(A)
print(f"\nDeterminant of A: {det_A:.2f}")


Determinant of A: -2.00


Inverse (if exists)

In [10]:
try:
    inv_A = np.linalg.inv(A)
    print(f"\nInverse of A:\n{inv_A}")
    print(f"\nA @ inv(A) (should be identity):\n{A @ inv_A}")
except Exception:
    print("\nMatrix is not invertible")


Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ inv(A) (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


============================================================================<br>
4. SOLVING LINEAR SYSTEMS (15 min - YOU KNOW THIS!)<br>
============================================================================

In [ ]:
print("\n5. SOLVING LINEAR SYSTEMS")
print("-" * 70)

Solve Ax = b<br>
Example: 2x + 3y = 8<br>
         3x + 4y = 11

In [11]:
A = np.array([[2, 3], [3, 4]])
b = np.array([8, 11])

In [12]:
print("System of equations:")
print("2x + 3y = 8")
print("3x + 4y = 11")
print("\nMatrix form Ax = b")
print(f"A =\n{A}")
print(f"b = {b}")

System of equations:
2x + 3y = 8
3x + 4y = 11

Matrix form Ax = b
A =
[[2 3]
 [3 4]]
b = [ 8 11]


In [13]:
x = np.linalg.solve(A, b)
print(f"\nSolution: x = {x}")
print(f"Verification: A @ x = {A @ x}")


Solution: x = [1. 2.]
Verification: A @ x = [ 8. 11.]


============================================================================<br>
5. USEFUL NUMPY FUNCTIONS (20 min)<br>
============================================================================

In [14]:
print("\n6. USEFUL FUNCTIONS")
print("-" * 70)


6. USEFUL FUNCTIONS
----------------------------------------------------------------------


In [15]:
data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(f"Data: {data}")

Data: [ 2  4  6  8 10 12 14 16 18 20]


In [16]:
print(f"\nSum: {np.sum(data)}")
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Std Dev: {np.std(data):.2f}")
print(f"Variance: {np.var(data):.2f}")
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")
print(f"Range: {np.ptp(data)}")  # peak-to-peak


Sum: 110
Mean: 11.0
Median: 11.0
Std Dev: 5.74
Variance: 33.00
Min: 2
Max: 20
Range: 18


Cumulative sum

In [17]:
print(f"\nCumulative sum: {np.cumsum(data)}")


Cumulative sum: [  2   6  12  20  30  42  56  72  90 110]


Dot product

In [18]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"\nv1 = {v1}")
print(f"v2 = {v2}")
print(f"Dot product: {np.dot(v1, v2)}")


v1 = [1 2 3]
v2 = [4 5 6]
Dot product: 32


Reshape

In [19]:
arr = np.arange(12)
print(f"\nOriginal: {arr}")
reshaped = arr.reshape(3, 4)
print(f"Reshaped (3x4):\n{reshaped}")


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print("\n" + "=" * 70)
print(" ✅ NUMPY BASICS COMPLETE!")
print("=" * 70)