In [ ]:
import numpy as np

my_matrix = np.random.randint(1, 101, (5, 5))

my_mean = np.mean(my_matrix)

my_std = np.std(my_matrix)

# set elements greater than 50 to 0

greater_50_elements = my_matrix[my_matrix > 50]
my_matrix[my_matrix > 50] = 0

print("Modified Matrix:\n", my_matrix)

print("Elements greater than 50 set to 0:\n", greater_50_elements)
print("Mean:", my_mean)
print("Standard Deviation:", my_std)    

Modified Matrix:
 [[25  0  0  1 22]
 [35 17  0 23  0]
 [38  0 24  0  1]
 [36 14  0  6 38]
 [15  0  0 39  0]]
Elements greater than 50 set to 0:
 [74 77 54 56 99 71 57 64 83 78]
Mean: 41.88
Standard Deviation: 27.320790618135486
